name: Update Threat Feeds
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  update_feeds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install requests python-whois jq
      - run: python scripts/fetch_and_parse.py
        env:
          OTX_API_KEY: ${{ secrets.OTX_API_KEY }}
          ABUSEIPDB_API_KEY: ${{ secrets.ABUSEIPDB_API_KEY }}
          IPINFO_API_KEY: ${{ secrets.IPINFO_API_KEY }}
          WHOIS_API_KEY: ${{ secrets.WHOIS_API_KEY }}
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/parsed/
          git commit -m "Update enriched threat feeds [skip ci]" || echo "No changes to commit"
          git push
