name: Update Threat Feeds

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Fetch and Normalize Feeds
        run: |
          python ingestion/fetch_feeds.py
          python ingestion/normalize_feeds.py
          python ingestion/merge_feeds.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "UTF Bot"
          git config --global user.email "utf-bot@users.noreply.github.com"
          git add output/
          git commit -m "Auto-update threat feeds [skip ci]" || echo "No changes to commit"
          git push
